### ISSUE TITLE
Create Full Example Application

### ISSUE THREAD

**Issue by ybur-yug** [beam-community/sheriff#10]
We should have an example application that shows a basic setup with one simple role for an `admin` type user or something like that.

This would include

- Guardian/ComeOnIn or something equivalent for basic authentication
- Some owned resource by user (posts would work, whatever)
- A very basic policy to allow admins to view all posts but a user can only see their own

I started on one but dont have time and with breaking changes from releasing so many early versions fast dont have the time right now.

**Comment by ybur-yug** [comment]
@yakschuss has volunteered to take this on.

**Comment by yakschuss** [comment]
I can take this

**Comment by doomspork** [comment]
Heck yeah @yakschuss!  Welcome to the party 🎉

**Comment by ybur-yug** [comment]
@yakschuss you should be able to reference the test cases to get the basics. Note the config that is necessary for the error handler, loader, and those pieces. If the docs aren't clear, let us know, we should make them better if it is not obvious.

**Comment by yakschuss** [comment]
@ybur-yug Just pinging you here to see if you had a chance to look at the PR.

**Comment by ybur-yug** [comment]
@yakschuss Been travelling, just getting back now. When I get caught up on work I will take a look.

**Comment by doomspork** [comment]
@yakschuss do you have a link to the PR in question?  Thanks again for your help! 😀

**Comment by doomspork** [comment]
Howdy @yakschuss!  ~~I'd love to incorporate your example, is it ready?~~

I found the repo https://github.com/yakschuss/sheriff_example, I'll update the README with a link 👍

**Comment by yakschuss** [comment]
@doomspork - I feel terrible I got pulled away. I'm not sure what was missing, if anything, but I'd take a closer look before linking.

**Comment by doomspork** [comment]
Thanks for the heads up @yakschuss 👍
